id: "9"
slug: product-of-array-except-self
title: Product of Array Except Self
difficulty: Medium
tags:
  - Array
  - Prefix Sum
  - Math
url: https://leetcode.com/problems/product-of-array-except-self/
text: |
  Given an integer array nums, return an array answer such that answer[i] is the
  product of all the elements of nums except nums[i]. The solution must run in
  O(n) time and without using division.

  Example 1:
  Input: nums = [1,2,3,4]
  Output: [24,12,8,6]

  Example 2:
  Input: nums = [-1,1,0,-3,3]
  Output: [0,0,9,0,0]

  Example 3:
  Input: nums = [2,3,4]
  Output: [12,8,6]

  Constraints:
  • 2 <= nums.length <= 10^5
  • -30 <= nums[i] <= 30
  • The product fits in 32-bit integer
snippets:
  - "def product_except_self(nums: list[int]) -> list[int]:"
  - "    n = len(nums)"
  - "    res = [1] * n"
  - "    prefix = 1"
  - "    for i in range(n):"
  - "        res[i] = prefix"
  - "        prefix *= nums[i]"
  - "    suffix = 1"
  - "    for i in range(n - 1, -1, -1):"
  - "        res[i] *= suffix"
  - "        suffix *= nums[i]"
  - "    return res"